In [1]:
import numpy as np

In [2]:
a=np.ones((3,4))

In [3]:
print(a)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [4]:
a=np.ones((3,4),dtype=int)
print(a)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [5]:
a=np.ones((3,4),dtype=str)
print(a)

[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]


In [6]:
a=np.ones((3,4),dtype=bool)
print(a)

[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


In [7]:
a=np.zeros((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
a=np.zeros((3,4),dtype=str)
print(a)

[['' '' '' '']
 ['' '' '' '']
 ['' '' '' '']]


In [9]:
a=np.zeros((3,4),dtype=bool)
print(a)

[[False False False False]
 [False False False False]
 [False False False False]]


In [10]:
print(a.ndim)

2


In [11]:
print(a.dtype)

bool


In [12]:
##This is comment


In [13]:
a=np.empty((3,4))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [14]:
a=np.empty((3,4),dtype=int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
