In [1]:
import numpy as np

In [6]:
a=np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
## to print even no 
a=np.arange(2,13,2)
print(a)

[ 2  4  6  8 10 12]


# linespace:-

In [10]:
a=np.linspace(1,5,4)
print(a)

[1.         2.33333333 3.66666667 5.        ]


# reshap

In [12]:
b=np.arange(1,21)
print(b)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [13]:
c=b.reshape(2,10)
print(c)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [14]:
c=b.reshape(2,5,2)
print(c)

[[[ 1  2]
  [ 3  4]
  [ 5  6]
  [ 7  8]
  [ 9 10]]

 [[11 12]
  [13 14]
  [15 16]
  [17 18]
  [19 20]]]


# ravel

In [15]:
c.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# flatten

In [16]:
b.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

# transpose

In [21]:
d=np.arange(1,11)
print(d)


[ 1  2  3  4  5  6  7  8  9 10]


In [26]:
e=d.reshape(2,5)
print(e)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [27]:
e.transpose()

array([[ 1,  6],
       [ 2,  7],
       [ 3,  8],
       [ 4,  9],
       [ 5, 10]])