In [1]:
import numpy as np 
import random

In [2]:
# to generate a random values in the 1D or 2D array but the values is b/w the 0 and 2 

In [3]:
np.random.random(1)

array([0.19799864])

In [4]:
np.random.random(5)

array([0.29953249, 0.37702715, 0.76503988, 0.28925264, 0.73242391])

In [5]:
np.random.random((3,3))

array([[0.49853219, 0.19484309, 0.5089504 ],
       [0.65410705, 0.84588938, 0.86652903],
       [0.86384897, 0.6514278 , 0.02501189]])

In [6]:
# to display the int values 

In [7]:
np.random.randint(1,4)

3

In [8]:
# for 2D matrix 

In [9]:
np.random.randint(1,7,(3,3))

array([[4, 5, 4],
       [5, 1, 4],
       [6, 3, 4]])

In [10]:
# for 3D 

In [11]:
np.random.randint(1,5,(2,3,3))

array([[[2, 3, 1],
        [1, 3, 2],
        [2, 1, 2]],

       [[2, 2, 1],
        [3, 2, 1],
        [3, 2, 3]]])

In [12]:
# now if we have to use the same random values again and again than we have to use the seed function 

In [13]:
np.random.seed(10)
np.random.randint(1,4,(3,3))

array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [14]:
np.random.seed(10)
np.random.randint(1,4,(3,3))


array([[2, 2, 1],
       [1, 2, 1],
       [2, 2, 1]])

In [15]:
# another method to prnt the random values 

In [16]:
np.random.rand(4)

array([0.02517173, 0.70920801, 0.26556613, 0.26360285])

In [17]:
np.random.rand(3,3)

array([[0.15037787, 0.68381843, 0.81660184],
       [0.33607158, 0.89081653, 0.19812181],
       [0.03061665, 0.87761494, 0.72743551]])

In [18]:
# now if we have to print the +ve and -ve values 

In [19]:
np.random.randn(4)

array([-1.08684028,  0.12055902,  1.40202525, -0.4342591 ])

In [20]:
np.random.randn(3,3)

array([[-1.25424191,  0.33157855, -0.30860049],
       [-0.15373549,  0.67893119, -1.91355421],
       [-0.94245806, -1.74554298, -1.02094527]])

In [21]:
# now if we have the selected values like list and have to select the random values form it 

In [22]:
x=[1,2,3,4,5,6,7,8]
np.random.choice(x)

5

In [23]:
# it is used to shuffle the list 

In [24]:
np.random.permutation(x)

array([8, 4, 6, 2, 5, 7, 1, 3])

In [25]:
# another method 

In [26]:
np.random.shuffle(x)

In [27]:
print(x)

[2, 7, 4, 6, 5, 3, 8, 1]
