In [1]:
import numpy as np

In [2]:
one=np.array([1,2,3,4])
print(one)

[1 2 3 4]


In [3]:
one.dtype

dtype('int32')

In [4]:
two=np.array([[1,2,3,4],[5,6,7,8]])
print(two)

[[1 2 3 4]
 [5 6 7 8]]


In [5]:
two.dtype

dtype('int32')

In [6]:
two.size

8

In [7]:
one.size

4

In [8]:
one.shape

(4,)

In [9]:
two.shape

(2, 4)

In [10]:
one.ndim

1

In [11]:
two.ndim

2

In [12]:
print(one)

[1 2 3 4]
