In [1]:
import numpy as np
a=np.arange(1,10).reshape(3,3)
b=np.arange(1,10).reshape(3,3)

In [2]:
print(a)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [3]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [4]:
np.add(a,b)

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [5]:
a-b

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [6]:
np.subtract(a,b)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [7]:
a/b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [8]:
np.divide(a,b)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [9]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [10]:
np.multiply(a,b)

array([[ 1,  4,  9],
       [16, 25, 36],
       [49, 64, 81]])

In [11]:
a@b

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [12]:
a.dot(b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [13]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [14]:
a.max()

9

In [15]:
a.argmax()

8

In [16]:
a.max(axis=0)

array([7, 8, 9])

In [17]:
a.max(axis=1)

array([3, 6, 9])

In [18]:
a.min()

1

In [19]:
a.argmin()

0

In [20]:
a.min(axis=0)

array([1, 2, 3])

In [21]:
a.min(axis=1)

array([1, 4, 7])

In [22]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
a.sum()

45

In [24]:
a.sum(axis=0)

array([12, 15, 18])

In [25]:
a.sum(axis=1)

array([ 6, 15, 24])

In [26]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [27]:
np.mean(a)

5.0

In [28]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [29]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [30]:
np.log10(a)

array([[0.        , 0.30103   , 0.47712125],
       [0.60205999, 0.69897   , 0.77815125],
       [0.84509804, 0.90308999, 0.95424251]])